apache2:
  build: apache2
  hostname: SITE_HOSTNAME
  restart: always
  ports:
    - "443:443"
    - "80:80"
  links:
    - cms
cms:
  build: cms
  restart: always
  ports:
    - "8080:8080"
  links:
   - postgres
   - mail
  environment:
    CATALINA_OPTS: "-XX:MaxPermSize=256m -Xms2048m -Xmx2048m"
    CMS_DB_PASSWORD: thisIsMy1stSecretCMSdbpwd
    CMS_DB_USER: cms
postgres:
  build: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: thisIsTheNo1MasterPassword
    CMS_DB_PASSWORD: thisIsMy1stSecretCMSdbpwd
  labels:
    io.enonic.backup.enable: "yes"
    io.enonic.backup.prescripts: "/usr/local/bin/backup-pre.sh"
    io.enonic.backup.postscripts: "/usr/local/bin/backup-post.sh"
    io.enonic.backup.data: "/backup"
  volumes_from:
    - postgresstorage
  ports:
   - "5432:5432"
postgresstorage:
  image: postgres:9.4.1
  command: "Postgres storage container"
  volumes:
    - /var/lib/postgresql/data
mail:
  image: enoniccloud/postfix
  hostname: SITE_HOSTNAME
  restart: always
