#!/bin/sh

LC_CTYPE=en_US.UTF-8
SVN=`which svn`

echo Changing to Bundles directory...
mkdir -p "/Library/Application Support/TextMate/Bundles"
cd "/Library/Application Support/TextMate/Bundles"

if [ -d "/Library/Application Support/TextMate/Bundles/Lua.tmbundle" ]; then
	echo Lua bundle already exists - updating...
	$SVN up "Lua.tmbundle"
else
	echo Checking out Lua bundle...
	$SVN --username anon --password anon co "http://svn.textmate.org/trunk/Bundles/Lua.tmbundle/"
fi

echo Reloading bundles in TextMate...
osascript -e 'tell app "TextMate" to reload bundles'